from models.network import EncodeAttentionQnM1, FeedForward, Average
from models.network2 import EncodeAttentionQMnM1M2
from models.network3 import EncodeAttentionQMQnMM
from models.network4 import EncodeFeedForwardQMnMM
from models.network5 import EncodeAttentionQMnM1M2M3
from models.network6 import EncodeAttentionQMnM1M2M3NoFF
from models.network7 import EncodeSmallAttentionQMnM1M2M3NoFF